services:
  - type: worker
    name: telegram-bot
    runtime: python
    repo: https://github.com/d-romeo/telegram-python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
